name: Automatic Merge

on:
  workflow_dispatch:
  workflow_run:
    workflows: Automatic Merge
    branches: l10n_crowdin_v5
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 23 * * *'

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LOG: "DEBUG"  # or "DEBUG"
          MERGE_LABELS: ""
          UPDATE_LABELS: ""
