name: Automatic download json files

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 22 * * *'

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: crowdin
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run pack-extractor

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:            
          commit_message: "feat: automatic json extract to traslate"
